Misc Gyro Stuff
Team4761/2017-Robot-Code pull request #34
Opened 2017-02-11 01:10 UTC by jakebacker

2017-02-11 01:14 UTC, simon-andrews requested changes

2017-02-11 01:14 UTC, simon-andrews commented on .classpath
> +	<classpathentry kind="lib" path="C:/Users/Brian Shin/workspace/2017-Robot-Code/lib/jar/Robockets-Commons-2.0.0.jar"/>
fail

2017-02-11 01:14 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
> +import org.robockets.steamworks.commands.*;
no

2017-02-11 01:14 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
> +	public static Command toggleDriveMode;
Why is this single one static?

2017-02-11 01:14 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
> +		SmartDashboard.putNumber("GyroP", drivetrain.gyroPID.getP());
Don't change anything for now, but be ready to use the SmartDashboard dumper when that's merged.

2017-02-11 01:14 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
> +		SmartDashboard.putNumber("drivetrain setpoint", drivetrain.encoderPID.getSetpoint());
Wouldn't this be an encoder for one pod?

Also same thing with the SmartDashboard dumper from above.

2017-02-11 01:14 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
> +		SmartDashboard.putNumber("Estimated Distance", RobotMap.leftEncoder.get() * (1.0f/33.0f)); // This has about a 1 inch error after about a foot and a half
Use the `Encoder.getDistance()` method.

2017-02-11 01:14 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
>  	public void teleopPeriodic() {
None of this new stuff should be in teleopPeriodic

2017-02-11 01:23 UTC, jakebacker commented on src/org/robockets/steamworks/Robot.java
> +		SmartDashboard.putNumber("drivetrain setpoint", drivetrain.encoderPID.getSetpoint());
Will be fixed when driving-pid-iterator and driving-pid is merged into drivetrain.

2017-02-11 01:23 UTC, jakebacker commented on src/org/robockets/steamworks/Robot.java
> +		SmartDashboard.putNumber("Estimated Distance", RobotMap.leftEncoder.get() * (1.0f/33.0f)); // This has about a 1 inch error after about a foot and a half
Will be fixed when driving-pid-iterator and driving-pid is merged into drivetrain.

2017-02-11 01:25 UTC, jakebacker commented
Don't merge yet until driving-pid and driving-pid-iterator is merged into drivetrain

2017-02-12 00:34 UTC, simon-andrews requested changes

2017-02-12 00:34 UTC, simon-andrews commented on src/org/robockets/steamworks/DrivePodOutput.java
> +	public DrivePodOutput(SpeedController c1, SpeedController c2) {
We only have one speed controller per drivepod.

2017-02-12 00:34 UTC, simon-andrews commented on src/org/robockets/steamworks/DrivePodOutput.java
> +	 * @param c2 Right side speed controller
Shouldn't these say front and back? Not that it matters, since there's only one speed controller now.

2017-02-12 00:34 UTC, simon-andrews commented on src/org/robockets/steamworks/DrivePodOutput.java
> +public class DrivePodOutput implements PIDOutput {
Do we even need this now that drivepods only have one speed controller?

2017-02-12 00:34 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
> +		autonomousCommand = new AutoTest(); // This breaks things
What's broken by it? Can we fix it?

2017-02-12 00:34 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
> +		autonomousCommand = new AutoTest(); // This needs to be here or else things break
What breaks if we remove it? Can we fix that?

2017-02-12 00:34 UTC, simon-andrews commented on src/org/robockets/steamworks/drivetrain/Drivetrain.java
> +    public void setDistanceInInches(double distance) {
Method name is kinda clunky.

2017-02-12 00:34 UTC, simon-andrews commented on src/org/robockets/steamworks/subsystems/GearIntake.java
> +		return false;//RobotMap.gearInputBreakbeamSensor.get();
Did fixing the port conflict with the encoder fix this issue? Should we undo this?

2017-02-12 16:10 UTC, jakebacker commented on src/org/robockets/steamworks/DrivePodOutput.java
> +public class DrivePodOutput implements PIDOutput {
Yes

2017-02-12 16:18 UTC, simon-andrews approved these changes

2017-02-12 16:18 UTC, merged