Drivetrain
Team4761/2017-Robot-Code pull request #41
Opened 2017-02-18 04:23 UTC by bshin100

Drivetrain became the new master but how about master being master?

2017-02-18 22:41 UTC, UnknownSilicon requested changes

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/Robot.java
> +
Why is there a new line here?

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/Robot.java
> +	public static IntakeFlap intakeFlap;
This should be with the other subsystems

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/Robot.java
>  		drivetrain.gyroPID.setSetpoint(SmartDashboard.getNumber("GyroSetpoint", 0));
No.

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/RobotMap.java
> +
Remove new line

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/commands/ExtraSpace.java
> +import org.robockets.commons.RelativeDirection;
Add new line

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/commands/KillEverything.java
> +    	Robot.intakeFlap.stop();
Ok... This might just be better in `initialize()`

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/commands/MakeExtraSpace.java
> +		return false;
This needs to be fixed

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/commands/MaxFillElevator.java
> +import org.robockets.commons.RelativeDirection;
New line

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/commands/MoveConveyor.java
> +        return isTimedOut();
This DOES need the `forever` thing

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/commands/Shoot.java
> +import org.robockets.commons.RelativeDirection;
Should be with the other import from above

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/commands/Shoot.java
Remove new line

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/commands/SpinSpinners.java
> +
Remove new line

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/drivetrain/DriveOnArc.java
> +	private double radius;
Indented too much

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/drivetrain/Turn.java
>  import org.robockets.steamworks.Robot;
New line

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/intakeflap/IntakeFlap.java
> +	}
Why?

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/intakeflap/IntakeFlap.java
> +	}
Bad indentation

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/intakeflap/IntakeFlap.java
> +    	else lastState = IntakeState.FUEL;
No. Just use normal `if` syntax

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/intakeflap/IntakeToPos.java
> +import org.robockets.steamworks.Robot;
New line

2017-02-18 22:41 UTC, jakebacker commented on src/org/robockets/steamworks/intakeflap/MoveIntakeFlap.java
> +import org.robockets.commons.RelativeDirection;
New line

2017-02-20 16:45 UTC, simon-andrews requested changes

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/GyroPIDOutput.java
> +    	Robot.drivetrain.driveArcade(0, output);
:confounded:

I don't think this will work the way you expect it to.

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/OI.java
> +    public static Joystick launchpad = new Joystick(3);
Can we get comments on the other three?

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
>  	private SendableChooser<Command> autonomousChooser;
:+1:

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/autonomous/AutoTest.java
> +    	addSequential(new DriveStraight(5, 24));
Worth noting that this will not drive forward the right distance anymore.

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/camera/Webcam.java
> +		SmartDashboard.putNumber(RobotMap.SmartDashboardKey.kCameraExposure, 75);
This will go back to one since we're on Logitech C270s now.

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/camera/Webcam.java
> +		exposure = (int) SmartDashboard.getNumber(RobotMap.SmartDashboardKey.kCameraExposure, 75);
Default exposure ought to be a variable I guess.

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/commands/KillEverything.java
> +    	setTimeout(0.2);
![REEEEEEEE](https://i.imgur.com/IETAF3w.jpg)

Just have `isFinished()` return true.

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/commands/MakeExtraSpace.java
> +		return false;
:exclamation:

Do we still have the breakbeam thing?

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/drivetrain/DriveStraight.java
> +        return leftLsg.hasNext() || rightLsg.hasNext();
Broken! Must be inverted!

2017-02-20 16:45 UTC, simon-andrews commented on src/org/robockets/steamworks/intakeflap/ToggleIntakeFlap.java
> +    	setTimeout(1);
We have position servos now so we don't need to rely on time.

2017-02-20 16:46 UTC, jakebacker commented on src/org/robockets/steamworks/GyroPIDOutput.java
> +    	Robot.drivetrain.driveArcade(0, output);
First arg is translation speed, second is rotation speed

2017-02-20 16:47 UTC, jakebacker commented on src/org/robockets/steamworks/OI.java
> +    public static Joystick launchpad = new Joystick(3);
???

2017-02-20 16:49 UTC, jakebacker commented on src/org/robockets/steamworks/commands/MakeExtraSpace.java
> +		return false;
Apparently not

2017-02-20 16:50 UTC, jakebacker commented on src/org/robockets/steamworks/drivetrain/DriveStraight.java
> +        return leftLsg.hasNext() || rightLsg.hasNext();
???

2017-02-20 21:57 UTC, simon-andrews commented on src/org/robockets/steamworks/OI.java
> +    public static Joystick launchpad = new Joystick(3);
The first `Joystick` (not shown) has a comment indicating that it's the Xbox controller. I'd like comments for the other three `Joystick`s.

2017-02-20 21:58 UTC, simon-andrews commented on src/org/robockets/steamworks/camera/Webcam.java
> +		SmartDashboard.putNumber(RobotMap.SmartDashboardKey.kCameraExposure, 75);
To add on to this, 1-5 is normal for driving, and 0 is for vision.

2017-02-21 16:38 UTC, UnknownSilicon approved these changes

2017-03-05 19:20 UTC, merged