Bag day
Team4761/2017-Robot-Code pull request #43
Opened 2017-02-24 19:01 UTC by simon-andrews

2017-02-24 19:31 UTC, UnknownSilicon requested changes

2017-02-24 19:31 UTC, jakebacker commented on src/org/robockets/steamworks/Robot.java
> +    	Robot.shooter.shooterPIDController.setPID(SmartDashboard.getNumber("Edit Shooter PID P value", 0.01), SmartDashboard.getNumber("Edit Shooter PID I value", 0.001), SmartDashboard.getNumber("Edit
This should be splint into multiple lines for readability

2017-02-24 19:31 UTC, jakebacker commented on src/org/robockets/steamworks/RobotMap.java
Remove extra new lines

2017-02-24 19:31 UTC, jakebacker commented on src/org/robockets/steamworks/climber/Climb.java
> +		System.out.println(RobotMap.powerDistPanel.getCurrent(RobotMap.climberPdpPort));
Remove print

2017-02-24 19:31 UTC, jakebacker commented on src/org/robockets/steamworks/climber/Climb.java
> +			System.out.println("TEST");
Remove print

2017-02-24 19:31 UTC, jakebacker commented on src/org/robockets/steamworks/climber/Climber.java
> +		//}
Reformat this block

2017-02-24 19:31 UTC, jakebacker commented on src/org/robockets/steamworks/commands/WaitUntilSpeed.java
> +    	System.out.println(Robot.shooter.shooterPIDController.onTarget());
Remove print

2017-02-28 00:19 UTC, bshin100 commented on src/org/robockets/steamworks/commands/WaitUntilSpeed.java
> +        return Robot.shooter.shooterPIDController.onTarget();
Aren't the PID.onTarget() methods dead?

2017-02-28 00:20 UTC, bshin100 commented on src/org/robockets/steamworks/drivetrain/Joyride.java
> +    		SmartDashboard.putNumber("LeftStickVal", leftStick);
We don't need these anymore

2017-02-28 00:25 UTC, UnknownSilicon approved these changes

2017-02-28 00:25 UTC, bshin100 approved these changes
👍 Be sure to remove the prints.

2017-02-28 01:13 UTC, simon-andrews commented on src/org/robockets/steamworks/climber/Climber.java
> +	public double STALLING_THRESHOLD = 90; // The stalling current of the subsystem motor.
This seems high.

2017-02-28 01:13 UTC, simon-andrews commented on src/org/robockets/steamworks/drivetrain/Joyride.java
> +    		SmartDashboard.putNumber("LeftStickVal", leftStick);
They're nice to have for debugging. Which I suspect we'll do at least once since our joysticks are trash.

2017-02-28 01:13 UTC, simon-andrews commented on src/org/robockets/steamworks/drivetrain/Turn.java
> +	private final double DIAMETER = 29;
Units?

2017-02-28 01:14 UTC, simon-andrews commented
I can't approve my own pull requests. Looks good though.

2017-02-28 01:31 UTC, simon-andrews commented
Merge this and you're cut.

2017-02-28 21:54 UTC, simon-andrews commented
![Scissors](http://pngimg.com/uploads/scissors/scissors_PNG1.png)

2017-03-04 00:14 UTC, jakebacker commented on src/org/robockets/steamworks/commands/WaitUntilSpeed.java
> +        return Robot.shooter.shooterPIDController.onTarget();
Yes and no... We need to test it

2017-03-04 00:15 UTC, jakebacker commented on src/org/robockets/steamworks/climber/Climber.java
> +	public double STALLING_THRESHOLD = 90; // The stalling current of the subsystem motor.
It is, we were getting really weird values when we were testing.

2017-03-05 19:14 UTC, merged