Drivetrain
Team4761/2017-Robot-Code pull request #6
Opened 2017-01-08 21:12 UTC by jakebacker

2017-01-08 21:17 UTC, simon-andrews requested changes
More enums and constants please.

2017-01-08 21:17 UTC, simon-andrews commented on src/org/robockets/steamworks/OI.java
> +    public static Joystick joystick = new Joystick(0);
Port number should be in its own constant.

2017-01-08 21:17 UTC, simon-andrews commented on src/org/robockets/steamworks/RobotMap.java
> +    public static TalonSRX frontLeft = new TalonSRX(0);
Port number should be in its own constant.

2017-01-08 21:17 UTC, simon-andrews commented on src/org/robockets/steamworks/RobotMap.java
> +    public static TalonSRX frontRight = new TalonSRX(1);
Port number should be in its own constant.

2017-01-08 21:17 UTC, simon-andrews commented on src/org/robockets/steamworks/RobotMap.java
> +    public static TalonSRX backLeft = new TalonSRX(2);
Port number should be in its own constant.

2017-01-08 21:17 UTC, simon-andrews commented on src/org/robockets/steamworks/RobotMap.java
> +    public static TalonSRX backRight = new TalonSRX(3);
Port number should be in its own constant.

2017-01-08 21:17 UTC, simon-andrews commented on src/org/robockets/steamworks/commands/Drive.java
> +            Robot.drivetrain.driveArcade(0.5*speed, offset*0.5*speed);
What is 0.5?

2017-01-08 21:17 UTC, simon-andrews commented on src/org/robockets/steamworks/commands/GottaGoFast.java
> +        translate = OI.joystick.getRawAxis(1);
Button number should be in its own constant.

2017-01-08 21:17 UTC, simon-andrews commented on src/org/robockets/steamworks/commands/GottaGoFast.java
> +        rotate = OI.joystick.getRawAxis(4);
Button number should be in its own constant.

2017-01-08 21:18 UTC, simon-andrews commented on src/org/robockets/steamworks/Robot.java
> +		drive = new GottaGoFast();
Doesn't match up with constructor.

2017-01-08 21:48 UTC, simon-andrews requested changes

2017-01-08 21:48 UTC, simon-andrews commented on src/org/robockets/steamworks/commands/GottaGoFast.java
> +        rotate = OI.joystick.getRawAxis(PortNumbers.JOYSTICK_ROTATE_AXIS);
Make names more Xbox-y.

2017-01-08 21:51 UTC, simon-andrews approved these changes

2017-01-08 21:51 UTC, merged

2017-01-11 00:48 UTC, bshin100 commented
👍